version: "3"
services:
  home:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: home
    restart: always
    expose:
      - 80
    networks:
      - nginx

networks:
  nginx:
    external: true
